name: artjournals
favicon: null
layout_spectrum: 0.81851
typography_spectrum: 0.19031
title: Art Journals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.2995763362850994
  rhythmicContrast: 0.5
purpose: []
